prismatic_box_controller:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # Position Controllers ---------------------------------------
    prismatic_joint_controller:
      type: effort_controllers/JointVelocityController
      joint: box_joint
      pid: {p: 100000.0, i: 1000.0, d: 1000.0}
