prismatic_box_controller:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 500

    # Position Controllers ---------------------------------------
    prismatic_joint_controller:
      type: effort_controllers/JointVelocityController
      joint: box_joint
      pid: {p: 21800000.0, i: 10000000.0, d: 2000.0}
